[workspace]
members = [
	"fuse",
	"tool",
	"nros",
	"nrfs",
]

[profile.release]
debug = true # for flamegraph
lto = "fat"
opt-level = 3
codegen-units = 1

[profile.grcov]
inherits = "dev"
opt-level = 0
