[workspace]
members = [
	"fuse",
	"tool",
	"nros",
	"nrfs",
	"nrkv",
]

[profile.release]
debug = true # for flamegraph
lto = "fat"
opt-level = 3
codegen-units = 1

# Because otherwise key derivation, encryption etc is just too damn slow
[profile.dev.package."*"]
opt-level = 3
