[package]
name = "nros"
version = "0.1.0"
edition = "2021"

[dependencies.endian]
package = "nora_endian"
version = "0.1"

[dependencies.rangemap]
version = "1.0"

[dependencies.lz4_flex]
version = "0.9"
default-features = false
