[package]
name = "nrfs"
version = "0.1.0"
edition = "2021"

[dependencies.endian]
package = "nora_endian"
version = "0.1"

[dependencies.nros]
path = "../nros"

[dependencies.siphasher]
version = "0.3"
