[package]
name = "tool"
version = "0.1.0"
edition = "2021"

[dependencies.clap]
version = "3.2"
features = ["derive"]

[dependencies.chrono]
version = "0.4"

[target.'cfg(target_family = "unix")'.dependencies.nix]
version = "0.25"

[dependencies.nrfs]
path = "../nrfs"
