[package]
name = "tool"
version = "0.2.0"
edition = "2021"

[features]
trace = ["nrfs/trace"]

[dependencies.clap]
version = "3.2"
features = ["derive"]

[dependencies.chrono]
version = "0.4"

[dependencies.nrfs]
path = "../nrfs"
