[package]
name = "fuse"
version = "0.1.0"
edition = "2021"

[dependencies.fuser]
version = "0.11"
features = ["abi-7-19"]

[dependencies.libc]
version = "*"

[dependencies.nrfs]
path = "../nrfs"

[dependencies.arena]
path = "../../arena"

[dependencies.env_logger]
version = "0.9"

[dependencies.log]
version = "0.4.6"
features = ["max_level_trace", "release_max_level_debug"]
